# Generated by Django 5.2.1 on 2025-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equino',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
