# Generated by Django 5.2.1 on 2025-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinos', '0002_alter_equino_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equino',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='equino',
            name='genero',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='equino',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equinos_fotos/'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
